<?php

use Mockery as m;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-21 at 17:44:26.
 */
class Twitter_Bootstrap_Typography_LeadTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Twitter_Bootstrap_Typography_Lead
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Twitter_Bootstrap_Typography_Lead;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->object = null;
    }

    public function testLead()
    {
        $this->assertEquals('<p class="lead">test</p>', $this->object->lead('test'));
    }
}